#!/bin/bash

# Install CMake GUI
sudo apt-get install cmake-gui

# SFML Dependencies
sudo apt-get install libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev\
libxcb-image0-dev libfreetype6-dev libglew1.5-dev libjpeg-dev libsndfile1-dev\
libopenal-dev libflac-dev

# Joystick
sudo apt-get install libudev-dev
